### ISSUE TITLE
intersection of two meshes

### ISSUE THREAD

**Issue by ChristopherFowler** [cnr-isti-vclab/vcglib#141]
Do you guys have the capability of taking the intersection of two meshes?  This is a functionality available in igllib but it is a bear to get working.  I have used vcglib extensively since it works well for every purpose I have needed except this one.  Maybe I am missing it somewhere?

I'm looking for exactly this functionality:  Get the intersection of two meshes:
![Screen Shot 2020-10-28 at 1 53 33 PM](https://user-images.githubusercontent.com/5312716/97520285-3b310800-1971-11eb-9b50-52393c9b3041.jpg)

**Comment by goodengineer** [comment]
Have a good time of the day. Thank you Christopher for your good, in place, short and to the point illustrated question.

"
Do you guys have the capability of taking the intersection of two meshes?
Maybe I am missing it somewhere?
"
- What was prior to, what is the detailed history? In order to enable the specific functionality and in high quality of performance(comparing to iglib) it must needs to study as much in full and understand all the vcglib relevant code(in order not to miss pieces, how meshes are stored, how they are manipulated, is there already relevant functionality coded, if yes, then how to invoke it and/or how to enhance its performance). To study it is good to code up-while-reading code, the way which enhances the value of time and contributes better to understanding. I am advocating alone, by myself my approach mostly.
 
- Fast intuitive impulse solution in pseudo-pseudo code:

Way a:

initialize memory and clear intersection_mesh; Loop on longest containing mesh d.s.: if(mesh_a.component == mesh_b.component) then intersection_mesh.add(mesh_a.component);

Way b(a bit of constructive, non harming critic is okay): 

what and how to save traversing in looping? How we usually save loops? By some more, wire-register batch atomic operation like masks on bits: (yet very coars:) mesh_a(ENOR)(mesh_a (-) mesh_b)) = intersection_mesh.

?

**Comment by malomo** [comment]
Currently we do not support this functionality.
Actually, in meshlab we rely on the libigl implementation in [filter_mesh_booleans](../../meshlab/blob/master/src/meshlabplugins/filter_mesh_booleans/filter_mesh_booleans.cpp).
You can check it out if you want to perform the operation using the vcglib.
